// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ClickableItemSection: typeof import('./components/ClickableItemSection.vue')['default']
    CreateCategoryDialog: typeof import('./components/categories/CreateCategoryDialog.vue')['default']
    CreateProjectDialog: typeof import('./components/projects/CreateProjectDialog.vue')['default']
    CreateStatusSeparatorBtn: typeof import('./components/status/CreateStatusSeparatorBtn.vue')['default']
    CreateTeam: typeof import('./components/teams/CreateTeam.vue')['default']
    CreateTeamDialog: typeof import('./components/teams/CreateTeamDialog.vue')['default']
    DrawerOpenButton: typeof import('./components/Layout/DrawerOpenButton.vue')['default']
    DrawerUserMenu: typeof import('./components/Layout/DrawerUserMenu.vue')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./components/ExampleComponent.vue')['default']
    MainDrawer: typeof import('./components/Layout/MainDrawer/MainDrawer.vue')['default']
    MainToolbar: typeof import('./components/Layout/MainToolbar.vue')['default']
    ProjectsExpansionItem: typeof import('./components/Layout/MainDrawer/ProjectsExpansionItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamMembers: typeof import('./components/teams/TeamMembers.vue')['default']
    TeamsExpansionItem: typeof import('./components/Layout/MainDrawer/TeamsExpansionItem.vue')['default']
  }
}
